### ISSUE TITLE
Exception when installing the registry package

### ISSUE THREAD

**Issue by parasiteoflife** [netinvent/windows_tools#18]
This is what I got in pycharm:

```
Collecting windows-tools.registry==1.1.0
  Using cached windows_tools.registry-1.1.0-py3-none-any.whl.metadata (11 kB)
Collecting typing>=3.5.0 (from windows-tools.registry==1.1.0)
  Using cached typing-3.7.4.3.tar.gz (78 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [11 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 14, in <module>
    File "C:\Users\ink\PycharmProjects\dummy\.venv\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
      import setuptools.version
    File "C:\Users\ink\PycharmProjects\dummy\.venv\Lib\site-packages\setuptools\version.py", line 1, in <module>
      import pkg_resources
    File "C:\Users\ink\PycharmProjects\dummy\.venv\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
      register_finder(pkgutil.ImpImporter, find_on_path)
                      ^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


```

**Comment by deajan** [comment]
I'll need a bit more input here.
What platform, what python version ?
Did you run python from a venv ?

Do you have `setuptools` installed ?

**Comment by deajan** [comment]
Closing for lack of activity.
